[limits]
min_topics = 5
max_topics = 20
max_no_below = -1 # -1 means number_of_documents / 10
min_no_above = 0.1
[algorithm]
mu = 100 # number of individuals that will pass each generation
lambda = 20 # number of individuals that are generated at each generation
initial = 100 # initial population
generations = 10
tournament_size = 10 # number of individuals randomly selected for the selection tournament
[probabilities]
mutate = 0.2 # probability of mutation
component_mutation = 0.5 # probability of a mutation of each individual component
mate = 0.5 # probability of crossover (mating)
no_filter = 0.5 # probability that a new individual is created with no term filter (no_above = no_below = 1)
[mutate]
# if a component is selected for mutation, a random gaussian number with mu mean and sigma standard deviation is added to the component
# the default values for topics and no_below are selected to ensure some variation on these parameters,
# but they must be reviewed by the user. In particular, the topics.sigma must be adapted to the topics range,
# and the no_below.sigma must be chosen taking into account the number of the documents.
# alpha and beta usually are between 0 and 1 so the default values here are usually fine.
# no_above is also between 0 and 1 so the same consideration from alpha and beta applies.
# alpha_type is an integer and can be -1, 0 or 1 only, so the default value here is mostly fine to ensure
# some variation of this parameter.
topics.mu = 0
topics.sigma = 3
alpha_val.mu = 0
alpha_val.sigma = 1
beta.mu = 0
beta.sigma = 1
no_above.mu = 0
no_above.sigma = 1
no_below.mu = 0
no_below.sigma = 10
alpha_type.mu = 0
alpha_type.sigma = 2
